environment:
  matrix:
  - nodejs_version: "12"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn --ignore-engines
test_script:
  - node --version
  - npm --version
  - yarn test
build: off
